backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls', namespace='predict')),
]

backend/predict/urls.py
from django.urls import path, re_path
from . import views

app_name = "predict"

urlpatterns = [
    # predict_page1 predict_page2
    path('', views.predict_page1, name='prediction_page'),
    path('img/', views.predict_page2, name='image_prediction_page'),

    path('predict/', views.predict, name='prediction'),
    path('img-predict/', views.img_predict, name='image_prediction'),
    # path('item-predict/', views.item_predict, name='item_prediction_page'),

    path('topics/', views.view_topic, name='topics'),

    # path('results/', views.view_results, name='results'),
    # drf result ~ detail view ex)728
    path('results/', views.ViewResult.as_view(), name='results'),
    path('results/<int:pk>', views.SeeItemView.as_view(), name='results_detail'),

    path('view_results/', views.PostListView.as_view(), name='view_results'),

    # path('view_results/', views.view_results, name='view_results'),
    path('view_results_sort/', views.view_sorted_results, name='sorted_view_results'),

    re_path(r'^product/', views.ViewProduct.as_view(), name='product'),

    path('wordcloud/', views.view_wordcloud, name='wordcloud'),
]

backend/predict/models.py
# from django.contrib.postgres.fields import ArrayField
from django.db import models
import pandas as pd


class TimeStampedModel(models.Model):
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

def jsonfield_default_value():
    return {'coordi' : list()}

class PredResults(models.Model):
    name = models.CharField(max_length=80)
    img = models.CharField(max_length=80)
    review = models.TextField(max_length=256, default='default')
    price = models.CharField(max_length=80, default='default')
    man = models.FloatField(default= 0.0)
    woman = models.FloatField(default= 0.0)
    rating = models.FloatField(default= 0.0)
    # coordi = models.JSONField(null=True, default = jsonfield_default_value)
    coordi = models.CharField(max_length=80, default='default')
    cosine_sim = models.FloatField(default=0.0)

    def __str__(self):
        return f'{self.name}'

'''
id
name	main_category	sub_category	brand	
number	tags	price	season	gender	
like	view	sale	coordi	
age18	age19_23	age24_28	age29_33	age34_39	age40	
man	woman	
img	year	only_season	scaled_rating	review

coordi = ArrayField(
    ArrayField(
        models.CharField(max_length=10, blank=True), verbose_name= "coordi",
        size=8,
    ),
    size=8,
)
'''

# 장바구니 모델은 여기를 참조하게 될 것
class Product(models.Model):

    name = models.CharField(verbose_name="name", max_length=255, null=True)
    main_category = models.CharField(verbose_name="main_category", max_length=255, null=True)
    sub_category = models.CharField(verbose_name="sub_category", max_length=255, null=True)
    brand = models.CharField(verbose_name= "brand", max_length=255, null=True)
    number = models.CharField(verbose_name= "number", max_length=255, null=True)
    tags = models.CharField(verbose_name= "tags", max_length=255, null=True)
    price = models.CharField(verbose_name= "price", max_length=255, null=True)
    season = models.CharField(verbose_name= "season", max_length=255, null=True)
    # 리스트 필드
    gender = models.CharField(verbose_name="gender", max_length=255, null=True)

    like = models.FloatField(verbose_name= "like", null=True)
    view = models.FloatField(verbose_name= "view", null=True)
    sale = models.CharField(verbose_name= "sale", max_length=255, null=True)
    # 리스트 필드
    coordi = models.CharField(verbose_name="coordi", max_length=255, null=True)

    age18 = models.FloatField(verbose_name= "age18", null=True)
    age19_23 = models.FloatField(verbose_name= "age19_23", null=True)
    age24_28 = models.FloatField(verbose_name= "age24_28", null=True)
    age29_33 = models.FloatField(verbose_name= "age29_33", null=True)
    age34_39 = models.FloatField(verbose_name= "age34_39", null=True)
    age40 = models.FloatField(verbose_name= "age40", null=True)
    man = models.FloatField(verbose_name= "man", null=True)
    woman = models.FloatField(verbose_name= "woman", null=True)
    img = models.CharField(verbose_name= "img", max_length=255, null=True)
    year = models.CharField(verbose_name= "year", max_length=255, null=True)
    only_season = models.CharField(verbose_name= "only_season", max_length=255, null=True)
    scaled_rating = models.FloatField(verbose_name= "scaled_rating", null=True)
    review = models.CharField(verbose_name = "review", max_length=255, null=True)

    def __str__(self):
        return self.name

# 유저 프로필과 위시리스트의 연결고리
# 각 커스텀의 이름 기록
class Custom(TimeStampedModel):
    custom_name = models.CharField(verbose_name="custom_name", max_length=255, null = True)

# 하나의 커스텀 안에는 여러 위시리스트를 담을 수 있다.
class Wishlist(TimeStampedModel):
    custom = models.ForeignKey(Custom, on_delete = models.CASCADE, related_name = 'wishlist', null=True)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, related_name = 'wishlist', null=True)

    def __str__(self):
        return f'{self.custom} {self.product}'

# custom.wishlist를 통해 역참조 가능

backend/predict/views.py
from collections import OrderedDict

from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render,  get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView

from predict.embedding import *
from predict.list import *
from predict.models import PredResults, Product, Wishlist, Custom
from predict.serializers import PredSerializer
from predict.serializers import PredDetailSerializer

### RestFramework
from rest_framework.decorators import api_view
from rest_framework.generics import GenericAPIView, RetrieveAPIView
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response
from rest_framework import generics, filters
# from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.parsers import JSONParser

## Third Party
import json
from nltk.tokenize import word_tokenize
# from konlpy.tag import Okt
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
import ast
from timeit import default_timer as timer



'''
데이터 프레임 -> 로직 -> 추천 -> 결과 

뷰(view)   
'''
#############################################################
# => 데이터 선언
#   코사인유사도를 구한 행렬을 역순으로 정렬 -> 유사도가 높은 순의 인덱스로 정렬됨
#   시간 복잡도가 제일 오래 걸림 => 여기서 시간을 제일 많이 소모됨 => O(n*logn)
#   sim_sorted_ind=sim.argsort()[:,::-1]
sim_sorted_ind = np.load('predict/data/sim_sorted_after.npy')
df = pd.read_csv('predict/data/merged_df_최종.csv', index_col='Unnamed: 0')
img_df = load_img_feature()

################################################################
# embeddings.py에서 함수들 임포트

###################################################

df["tags"] = df["tags"].apply(lambda x: make_list(x))
df["review_tagged_cleaned"] = df["review_tagged_cleaned"].apply(lambda x: make_list(x))
df["coordi"] = df["coordi"].apply(lambda x: make_list(x))

######## mean_vector.npy 불러오는 것으로 아래 코드 해결

# topic modeling
# embedding.py
#

## Views.py ####################################

def predict_page1(request):
    return render(request, 'predict.html',
           {'category_list': category_list, 'coordi_list': coordi_list})

def predict_page2(request):
    return render(request, 'image_predict.html', {'list': category_list})

# view 함수
@csrf_exempt
@api_view(['POST'])
def predict(request):
    if request.method == 'POST':
        # unparsed_json = request.body.decode('utf-8')
        # postData = json.loads(unparsed_json)
        # print(postData)
        data = JSONParser().parse(request)
        print(data)
        print(data['main_category'])

        # {'main_category': '상의', 'coordi': '캐주얼', 'input_text': '여름', 'top_n': '30'}

        main_category = str(data['main_category']) # 로직, 로직
        coordi = str(data['coordi']) # 코디,코디
        input_text = str(data['input_text']) # input_text
        top_n = int(data['top_n']) # 50

        # 가방,모자,상의 <= 이런 양식으로 받아온다.
        # print(main_category)
        # print(coordi)

        if input_text == '가성비' :
            input_text = '가성'

        # coordi, category list 화
        main_category = main_category.split(",")
        coordi = coordi.split(",")

        print('카테고리 :', main_category)
        print('코디 :', coordi)
        print('인풋 텍스트 :', input_text)
        print('topn : ', top_n)

        # Make prediction
        try:
            tot_result = recsys(main_category, coordi, input_text)

            result = tot_result[:top_n]
            result = result.sort_values(by=["wv_cosine", "scaled_rating", "year"], ascending=False)

            print('1단계 :', result)
            print('2단계 :', result.columns)

            classification = result[['name', 'img', 'review', 'price', 'man', 'woman', 'scaled_rating', 'coordi', 'wv_cosine']]
            classification["coordi"] = classification["coordi"].apply(lambda x: make_list(x))

            name = list(classification['name'])
            img = list(classification['img'])
            review = list(classification['review'])
            price = list(classification['price'])
            woman = list(classification['woman'])
            man = list(classification['man'])
            rating = list(classification['scaled_rating'])
            coordi = list(classification['coordi'])  # coordi는 리스트 of 리스트
            cosine_sim = list(classification['wv_cosine'])

            print(name)
            print(coordi)

            records = PredResults.objects.all()
            records.delete()

            for i in range(len(classification)):
                PredResults.objects.create(name=name[i], img=img[i],
                                           review=review[i], price=price[i],
                                           woman=woman[i], man=man[i],
                                           rating=rating[i], cosine_sim=cosine_sim[i],
                                           coordi=', '.join(coordi[i]),
                                           # coordi={'coordi': coordi[i]}
                )
                # coordi = {'coordi': coordi[i]})
            print('DB 저장 완료')

            try:
                wordcloud(result)
            except:
                pass

            return JsonResponse({'name': name}, safe=False)

        except:
            return JsonResponse({'name': "해당되는 추천이 없습니다. 다시 입력해주세요"}, safe=False)

    # else:
    #     return render(request, 'predict.html', {'category_list': category_list, 'coordi_list': coordi_list})


# image classification view 함수
@csrf_exempt
@api_view(['GET', 'POST'])
def img_predict(request):

    if request.method == 'POST':
        data = JSONParser().parse(request)
        print(data)
        input_text = str(data['input_text'])
        top_n = int(data['top_n'])
        main_category = str(data['main_category'])
        print(input_text)
        print(top_n)
        print(main_category)
        print()
        if input_text == '가성비' :
            input_text = '가성'

        # input_text = data['input_text']
        # top_n = data['top_n']
        # main_category = data['main_category']

        print(input_text, top_n, main_category)
        # Make prediction
        try:
            start = timer()
            # Okt가 시간이 엄청 걸림

            string_list = word_tokenize(input_text)  # 리스트 형태

            vec_input = aggregate_vectors(string_list)
            # vec_input = word2vec.wv[input_text]
            print('1단계', vec_input[:10])

            mean_vector = np.load('predict/data/mean_vector.npy')

            # 인풋 임베딩 단어와 모든 상품간의 유사도 => 열벡터 생성
            cosine_sim = []
            for idx, vec in enumerate(mean_vector):
                vec1 = vec_input.reshape(1, -1)
                vec2 = vec.reshape(1, -1)
                cos_sim = cosine_similarity(vec1, vec2)[0][0]
                cosine_sim.append((idx, cos_sim))
            print('2단계', cosine_sim[:10])

            temp_sim = []
            for elem in cosine_sim:
                temp_sim.append(elem[1])

            temp_df = df.copy()
            temp_df['wv_cosine'] = temp_sim

            sim_df = temp_df[temp_df['main_category'].str.contains(main_category)]

            print('3단계', sim_df)

            name1 = sim_df['name'].values[0]
            name2 = sim_df['name'].values[1]
            name3 = sim_df['name'].values[2]

            print('4단계', name1, name2, name3)
            # 상위 3개의 그림과 비교
            img_score1 = img_sim(img_df, name1)  # 2000개 추출
            img_score2 = img_sim(img_df, name2)
            img_score3 = img_sim(img_df, name3)

            # 3개 간 교집합
            img_score = list(set(img_score1) & set(img_score2) & set(img_score3))

            print('5단계', img_score[:10])
            # 이미지 유사도
            temp = sim_df[sim_df['name'].isin(img_score)]
            print('6단계', temp)
            print('7단계', temp.columns)
            temp = temp.sort_values(by='wv_cosine', ascending=False)
            temp = temp[:top_n]

            print('8단계', temp)

            temp = temp.sort_values(by=['wv_cosine', 'scaled_rating', 'year'], ascending=False)
            # print(temp.columns)
            print('9단계', temp)

            # print('7단계', type(temp['review_tagged_cleaned'][0]))

            classification = temp[['name', 'img', 'review', 'price','man', 'woman', 'scaled_rating', 'coordi', 'wv_cosine']]

            name = list(classification['name'])
            img = list(classification['img'])
            review = list(classification['review'])
            price = list(classification['price'])
            woman = list(classification['woman'])
            man = list(classification['man'])
            rating = list(classification['scaled_rating'])
            coordi = list(classification['coordi']) # coordi는 리스트 of 리스트
            cosine_sim = list(classification['wv_cosine'])

            print(name)
            print(coordi)

            records = PredResults.objects.all()
            records.delete()

            for i in range(len(classification)):
                PredResults.objects.create(name=name[i], img=img[i],
                                           review=review[i], price=price[i],
                                           woman= woman[i], man = man[i],
                                           rating= rating[i], cosine_sim = cosine_sim[i],
                                           coordi= ', '.join(coordi[i]) )
                                           # coordi= {'coordi': coordi[i]} )
                                           # coordi = {'coordi': coordi[i]})
            #### Wordcloud 만들기
            try:
                wordcloud(temp)
            except:
                pass

            end = timer()
            time = end - start

            return JsonResponse({'name': name, 'time': time}, safe=False)

        except:
            return JsonResponse({'name': "해당되는 추천이 없습니다. 다시 입력해주세요"}, safe=False)


# @api_view(['GET', 'POST'])
# def view_results(request):

backend/templates/image_predict.html
{% extends "base.html" %}
{% load static %}

{% block main %}

<style>

.container h1 {
    font-family: "Nanum Gothic";
    font-weight: bolder;
}

.container .form-group {
    font-family: "Nanum Gothic";
}

.container label {
    font-weight: bolder;
}

</style>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">CNN-Recommendation Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">

                <div>name : <span id="name"></span></div>
                <div>time : <span id="time"></span></div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>

        </div>
    </div>
</div>

<h1 style="text-align: center; margin-top: 2rem; margin-bottom: 1rem;">Word2vec-CNN-Recommendation Input 🍊</h1>
<hr>

<div class = "container">

<div class="container pt-5">
    <div class="row justify-content-md-center">
{#        column grid medium -> 12/4(3분할) number of 4#}
        <div class="col-md-6">
            <form action="" id="post-form">
                {% csrf_token %}

                <div class="form-group">
                    <label for="main_category">카테고리 입력</label>
                    <select class="form-control" id = "main_category"  required>
                      <option selected> 메인 카테고리를 선택해주세요  </option>
                      {% for elem in list %}

                        <option value={{ elem }}>{{ elem }}</option>

                      {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="input_text">키워드 입력</label>
                    <input type="text" class="form-control" id="input_text"
                           placeholder="키워드를 입력해주세요 (명사 위주)" required>
                </div>

                <div class="form-group">
                    <label for="top_n">Top-N</label>
                    <input type="number" step="0.1" class="form-control" id="top_n"
                           placeholder="양의 정수를 입력해주세요 (권장 20개 이상)" required>
                </div>
                <button style ='margin-top: 2rem;' type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">제출</button>
            </form>
        </div>


    </div>
</div>

</div>

<script>

    $(document).on('submit', '#post-form',function(e){
        // {# submit -> 연쇄 다음 이벤트 묵살 -> ajax 실행 #}
        e.preventDefault();
        $.ajax({
            type:'POST',
            //{#app = predict, reference url namespace => submit_prediction #}

            url:'{% url "predict:image_prediction" %}',
            dataType : "json",
            data: JSON.stringify({
                input_text:$('#input_text').val(),
                top_n:$('#top_n').val(),
                main_category:$('#main_category').val(),

                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                // action: 'post'
            }),

            success:function(json) {
                // {#form 보냄이 성공하면 적은 내용 사라짐#}
                document.forms["post-form"].reset();
                alert('오래 기다리셨습니다!');

                document.getElementById("name").innerHTML = json['name']
                document.getElementById("time").innerHTML = json['time']
                // {#document.getElementById("img").innerHTML = json['img']#}

            },
            error : function(xhr,errmsg,err) {
                console.log(error);
            }
        });
    })

</script>

{% endblock %}

backend/templates/predict.html
{% extends "base.html" %}
{% load static %}

{% block main %}

<style>

.container h1 {
    font-family: "Nanum Gothic";
    font-weight: bolder;
}

.container .form-group {
    font-family: "Nanum Gothic";
}

.container label {
    font-weight: bolder;
}

</style>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Contents-Topic based Recommendation Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">

                <div>name : <span id="name"></span></div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<h1 style="text-align: center; margin-top: 2rem; margin-bottom: 1rem;">Contents based Recommendation Input 🍊</h1>
<hr>

<div class = "container">

<div class="container pt-5">
    <div class="row justify-content-md-center">
{#        column grid medium -> 12/4(3분할) number of 4#}
        <div class="col-md-6">
            <form action="" id="post-form">
                {% csrf_token %}


                <div class="form-group">
                    <label for="main_category">카테고리</label><br>

                    {% for elem in category_list  %}
                    <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="main_category" value={{ elem }}>
                    <label class="form-check-label" for="main_category">{{elem}}</label>
                    </div>
                    {%  endfor %}

                </div>



                <div class="form-group">
                    <label for="coordi">코디</label><br>

                    {% for elem in coordi_list  %}
                    <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="coordi" value={{ elem }}>
                    <label class="form-check-label" for="coordi">{{elem}}</label>
                    </div>
                    {%  endfor %}
                    <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="coordi" value="">
                    <label class="form-check-label" for="coordi">없음</label>
                    </div>

                </div>

                <div class="form-group">
                    <label for="input_text">키워드 입력</label>
                    <input type="text" class="form-control" id="input_text"
                           placeholder="키워드를 입력해주세요 (예 : 조거바지, 흰티)" required>
                </div>

                <div class="form-group">
                    <label for="top_n">Top-N</label>
                    <input type="number" step="0.1" class="form-control" id="top_n"
                           placeholder="양의 정수를 입력해주세요" required>
                </div>
                <button style ='margin-top: 2rem;' type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">제출</button>
            </form>
        </div>

    </div>
</div>

</div>

<script>

    $(document).on('submit', '#post-form',function(e){
        // name이 같은 체크박스의 값들을 배열에 담는다.
        var main_category_checkboxValues = [];
        $("input[id='main_category']:checked").each( function(i) {
        main_category_checkboxValues.push($(this).val());
        });

        var coordi_checkboxValues = [];
        $("input[id='coordi']:checked").each( function(i) {
        coordi_checkboxValues.push($(this).val());
        });

        console.log(main_category_checkboxValues);
        console.log(coordi_checkboxValues);

        var main_category_string = main_category_checkboxValues.toString()
        var coordi_string = coordi_checkboxValues.toString()

        console.log(main_category_string);
        console.log(coordi_string);


        //{# submit -> 연쇄 다음 이벤트 묵살 -> ajax 실행 #}
        e.preventDefault();

        $.ajax({
            type:'POST',
            //{#app = predict, reference url namespace => submit_prediction #}

            url:'{% url "predict:prediction" %}',
            dataType : "json",
            // 데이터를 json 문자열로 변환
            data: JSON.stringify({
                input_text:$('#input_text').val(),
                top_n:$('#top_n').val(),
                coordi: coordi_string,
                main_category: main_category_string,
                // Django의 form csrf 토큰을 가져온다.
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                // action: 'post'
            }),

            success:function(json) {
                {#form 보냄이 성공하면 적은 내용 사라짐#}
                document.forms["post-form"].reset();
                alert('POST Success!');

                document.getElementById("name").innerHTML = json['name']


            },
            error : function(xhr,errmsg,err) {
                console.log(error);
            }
        });
    })

</script>


{% endblock %}

backend/templates/results.html
{% extends "base.html" %}

{% load static %}

{% block main %}

    <style>

    .card {
        border-radius: 1rem;
    }

    .container img {
      border-radius: 1rem;
    }

    .container h1, h5 {
        font-family: "Nanum Gothic";
        font-weight: bolder;
    }

    .container .card {
        margin : 0.5rem 1rem;
    }

    .container p {
        font-family: "Nanum Gothic";
    }

    </style>

    <h1 style="text-align: center; margin-top: 2rem; ">
            Recommendation </h1>

<div class="text-center" style=" margin-top: 2rem ;">
    <button
            type="button"
            onclick="location.href='{% url 'predict:sorted_view_results'%}?sort=rating' ">
            Rating sort
    </button>

    <button
            type="button"
            onclick="location.href='{% url 'predict:sorted_view_results'%}?sort=cosine_sim' ">
            Similarity
    </button>

    <button
            type="button"
            onclick="location.href='{% url 'predict:sorted_view_results'%}?sort=man' ">
            Man
    </button>

    <button
            type="button"
            onclick="location.href='{% url 'predict:sorted_view_results'%}?sort=woman' ">
            Woman
    </button>

</div>

<hr>
    <div class="container">

    <div class="container pt-5">
        <div class="row justify-content-md-center">
        {% for data in dataset %}

        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{{ data.img }}" alt="">
          <div class="card-body">
            <h5 class="card-title">{{ data.name }}</h5>
            <p class="card-text">{{ data.review }}</p>
            <p class="card-text" style="font-weight: bolder">{{ data.price }}</p>
              <p class="card-text" style="font-weight: bolder">Rate : {{ data.rating | floatformat:2 }}</p>
          </div>
        </div>

    {% endfor %}


    </div>
    </div>

<script src = "{% static 'js/magicgrid.js' %}"></script>

<!--<script type="text/javascript">-->

<!--  $(".rating_sort").click(function(e){-->

<!--      // -rating-->
<!--    var rating_sort = $(this).attr('name')-->
<!--    e.preventDefault();-->

<!--    $.ajax({ // .like 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.-->
<!--      type: "GET", // 데이터를 전송하는 방법을 지정-->

<!--      url: "{% url 'predict:sorted_view_results' %}", // 통신할 url을 지정-->
<!--      data: {-->
<!--          'rating_sort': rating_sort,-->
<!--          //'csrfmiddlewaretoken': '{{ csrf_token }}'-->
<!--      }, // 서버로 데이터 전송시 옵션-->

<!--      // dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단-->
<!--      // 서버측에서 전송한 Response 데이터 형식 (json)-->

<!--      success: function(){ // 통신 성공시 - 페이지 이동-->
<!--        alert('Sort Success!');-->
<!--        // window.location.reload()-->
<!--        window.location.href = "{% url 'predict:sorted_view_results' %}"-->
<!--      },-->
<!--      error: function(request, status, error){ // 통신 실패시 - 로그인 페이지 리다이렉트-->
<!--        // window.location.reload()-->
<!--        //  alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);-->
<!--      },-->
<!--    });-->
<!--  })-->
<!--</script>-->


{% endblock %}

backend/templates/topic_modeling.html
{% extends "base.html" %}
{% load static %}

{% block main %}

<h1 style="text-align: center; margin-top: 2rem; ">
Topic Modeling </h1>
<hr>

<div class = "container" style="margin-top: 5rem; text-align: center">
{% include "topic.html" %}
</div>


{% endblock %}

backend/templates/wordcloud.html
{% extends "base.html" %}

{% load static %}

{% block main %}
    <style>

    .card {
        border-radius: 1rem;
    }

    .container img {
      border-radius: 1rem;
    }

    .container h1, h5 {
        font-family: "Nanum Gothic";
        font-weight: bolder;
    }

    .container .card {
        margin : 0.5rem 1rem;
    }

    .container p {
        font-family: "Nanum Gothic";
    }

    </style>
    <h1 style="text-align: center; margin-top: 2rem; ">
            ☁️ Word Cloud ☁️ </h1>
    <hr>

    <div class="container" style="text-align: center">
    <div class="container pt-5">
        <div class="row justify-content-md-center">

        <img src="{% static '무신사.png' %}"
        style="width : 70%; height: 50%; margin-top: 1rem;">


    </div>
    </div>

<script src = "{% static 'js/magicgrid.js' %}"></script>





{% endblock %}